# Generated by Django 5.0.4 on 2026-06-17 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_user_can_post_properties_user_id_number_user_id_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="verification_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Verification"),
                    ("in_review", "In Review"),
                    ("verified", "Verified"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                help_text="Mirrors Agent/Company verification_status for consistent admin filtering",
                max_length=20,
            ),
        ),
    ]
