# Generated by Django 5.0.4 on 2026-05-19 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CommunityEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("image", models.ImageField(upload_to="events/")),
                (
                    "image_alt",
                    models.CharField(
                        blank=True,
                        help_text="Alt text — defaults to event name if left blank",
                        max_length=200,
                    ),
                ),
                ("event_date", models.DateField(help_text="Displayed as 'Month YYYY'")),
                ("is_active", models.BooleanField(default=True)),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="Lower = shown first"
                    ),
                ),
            ],
            options={
                "verbose_name": "Community Event",
                "verbose_name_plural": "Community Events",
                "ordering": ["order", "-event_date"],
            },
        ),
    ]
