# Generated by Django 5.0.4 on 2026-06-06 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Finish",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=120, unique=True)),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Bootstrap-icon class e.g. bi-stars",
                        max_length=60,
                    ),
                ),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="ProductCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=140, unique=True)),
                (
                    "use_type",
                    models.CharField(
                        choices=[
                            ("interior", "Interior"),
                            ("exterior", "Exterior"),
                            ("both", "Interior & Exterior"),
                        ],
                        default="interior",
                        max_length=10,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Bootstrap-icon class e.g. bi-paint-bucket",
                        max_length=60,
                    ),
                ),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "product categories",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="ValpaintProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=220, unique=True)),
                ("sku", models.CharField(blank=True, max_length=60)),
                (
                    "short_desc",
                    models.CharField(
                        blank=True, max_length=320, verbose_name="Short description"
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "applications",
                    models.TextField(
                        blank=True, help_text="Where / how to apply (one item per line)"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="valpaint/products/"
                    ),
                ),
                ("image_alt", models.CharField(blank=True, max_length=200)),
                (
                    "price_ngn",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Price (₦)",
                    ),
                ),
                (
                    "price_label",
                    models.CharField(
                        blank=True,
                        help_text="e.g. 'per 5 L tin' or 'Contact for quote'",
                        max_length=60,
                    ),
                ),
                ("is_featured", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("in_stock", models.BooleanField(default=True)),
                ("meta_title", models.CharField(blank=True, max_length=200)),
                ("meta_description", models.CharField(blank=True, max_length=320)),
                (
                    "valpaint_url",
                    models.URLField(
                        blank=True, verbose_name="Valpaint official product URL"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products",
                        to="valpaint.productcategory",
                    ),
                ),
                (
                    "finishes",
                    models.ManyToManyField(
                        blank=True, related_name="products", to="valpaint.finish"
                    ),
                ),
            ],
            options={
                "ordering": ["-is_featured", "name"],
            },
        ),
        migrations.CreateModel(
            name="ValpaintEnquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=140)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=30)),
                (
                    "location",
                    models.CharField(
                        blank=True, help_text="City / area in Nigeria", max_length=200
                    ),
                ),
                ("message", models.TextField()),
                (
                    "quantity",
                    models.CharField(
                        blank=True,
                        help_text="e.g. '10 tins', 'whole apartment'",
                        max_length=80,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("contacted", "Contacted"),
                            ("closed", "Closed"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="enquiries",
                        to="valpaint.valpaintproduct",
                    ),
                ),
            ],
            options={
                "verbose_name": "Valpaint Enquiry",
                "verbose_name_plural": "Valpaint Enquiries",
                "ordering": ["-created_at"],
            },
        ),
    ]
