# Generated by Django 5.0.4 on 2026-08-25 00:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0003_add_slot_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="listingpackage",
            name="area_specialist_spots",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="listingpackage",
            name="auto_boost_interval_days",
            field=models.PositiveIntegerField(
                default=13,
                help_text="Auto push-up fires every N days. Nestova offers 2 days fewer than PropertyPro per tier — meaning more frequent boosts at the same price: Manager=13d, Executive=7d, Gold=1d, Platinum=1d (PropertyPro equivalents: 15d, 9d, 3d, 2d)",
            ),
        ),
        migrations.AddField(
            model_name="listingpackage",
            name="banner_ads",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="listingpackage",
            name="homepage_logo",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="listingpackage",
            name="manual_boosts_per_cycle",
            field=models.PositiveIntegerField(
                default=0, help_text="Manual push-up credits per billing cycle"
            ),
        ),
        migrations.AddField(
            model_name="listingpackage",
            name="premium_gold_slots_per_cycle",
            field=models.PositiveIntegerField(
                default=0, help_text="Premium Gold listing (10×) slot credits per cycle"
            ),
        ),
        migrations.AddField(
            model_name="listingpackage",
            name="premium_slots_per_cycle",
            field=models.PositiveIntegerField(
                default=0, help_text="Premium listing (5×) slot credits per cycle"
            ),
        ),
        migrations.AddField(
            model_name="listingpackage",
            name="social_media_ads_per_cycle",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="listingpackage",
            name="sponsored_slots_per_cycle",
            field=models.PositiveIntegerField(
                default=0, help_text="Sponsored listing (20×) slot credits per cycle"
            ),
        ),
        migrations.AddField(
            model_name="usersubscription",
            name="last_auto_boost_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the last system auto-boost ran for this user",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="usersubscription",
            name="manual_boosts_remaining",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="usersubscription",
            name="next_auto_boost_at",
            field=models.DateTimeField(
                blank=True, help_text="When the next auto-boost should fire", null=True
            ),
        ),
        migrations.AddField(
            model_name="usersubscription",
            name="premium_gold_slots_remaining",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="usersubscription",
            name="premium_slots_remaining",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="usersubscription",
            name="sponsored_slots_remaining",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="listingpackage",
            name="duration_days",
            field=models.PositiveIntegerField(
                default=30, help_text="Subscription cycle length in days (30 = monthly)"
            ),
        ),
        migrations.AlterField(
            model_name="listingpackage",
            name="features",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Extra feature bullet points displayed on the pricing page",
            ),
        ),
        migrations.AlterField(
            model_name="listingpackage",
            name="is_default",
            field=models.BooleanField(
                default=False,
                help_text="Assign this plan automatically to new users (free tier)",
            ),
        ),
        migrations.AlterField(
            model_name="listingpackage",
            name="listing_limit",
            field=models.PositiveIntegerField(
                default=5,
                help_text="Max active listings allowed simultaneously under this plan",
            ),
        ),
        migrations.AlterField(
            model_name="listingpackage",
            name="slots_count",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Deprecated — use listing_limit instead",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="usersubscription",
            name="end_date",
            field=models.DateTimeField(
                blank=True,
                help_text="When the current subscription expires (null = free tier)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="usersubscription",
            name="initial_free_slots",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Free listing slots given on sign-up (admin-configurable)",
            ),
        ),
        migrations.AlterField(
            model_name="usersubscription",
            name="package",
            field=models.ForeignKey(
                blank=True,
                help_text="Currently active plan",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="listings.listingpackage",
            ),
        ),
        migrations.AlterField(
            model_name="usersubscription",
            name="start_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="usersubscription",
            name="total_slots",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Deprecated — listing capacity now comes from the package",
            ),
        ),
        migrations.AlterField(
            model_name="usersubscription",
            name="used_slots",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Deprecated — use active_listing_count property instead",
            ),
        ),
        migrations.CreateModel(
            name="PaymentRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference",
                    models.CharField(db_index=True, max_length=120, unique=True),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("paystack_response", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "package",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="listings.listingpackage",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
