# Generated by Django 5.0.4 on 2026-08-04 23:39

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BusinessPartnershipInquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=200)),
                ("business_name", models.CharField(blank=True, max_length=300)),
                ("email", models.EmailField(max_length=254)),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="City / Country of operation",
                        max_length=200,
                    ),
                ),
                ("website", models.URLField(blank=True)),
                (
                    "partnership_type",
                    models.CharField(
                        choices=[
                            (
                                "valpaint_distributor",
                                "Valpaint Distribution Partnership",
                            ),
                            (
                                "smartshield_installer",
                                "SmartShield Installer / Technician",
                            ),
                            (
                                "smartshield_investor",
                                "SmartShield Manufacturing Investor",
                            ),
                            (
                                "communications_supplier",
                                "Tech Gadget Supplier / Sourcing",
                            ),
                            (
                                "essentials_supplier",
                                "Home & Lifestyle Product Supplier",
                            ),
                            (
                                "tourism_hospitality",
                                "Tourism Hospitality Partner (Hotel/Resort/Airline)",
                            ),
                            ("tourism_agency", "Travel / Tourism Agency Partnership"),
                            ("media_influencer", "Media / Influencer Collaboration"),
                            (
                                "real_estate_developer",
                                "Real Estate Developer Partnership",
                            ),
                            ("general", "General Business Inquiry"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "business_size",
                    models.CharField(
                        choices=[
                            ("individual", "Individual / Freelancer"),
                            ("startup", "Startup (1–10 Employees)"),
                            ("sme", "SME (11–100 Employees)"),
                            ("large", "Large Business (100+ Employees)"),
                            ("corporation", "Corporation / Conglomerate"),
                        ],
                        default="individual",
                        max_length=20,
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        help_text="Describe what you're proposing and how you'd like to partner with Nestova"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("contacted", "Team Contacted"),
                            ("negotiation", "In Negotiation"),
                            ("active_partner", "Active Partner"),
                            ("declined", "Declined"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("admin_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("contacted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Business Partnership Inquiry",
                "verbose_name_plural": "Business Partnership Inquiries",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AcademyEnrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None
                    ),
                ),
                ("age", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "occupation",
                    models.CharField(
                        blank=True,
                        help_text="Current occupation or field of work",
                        max_length=200,
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="City / State of residence",
                        max_length=200,
                    ),
                ),
                (
                    "program",
                    models.CharField(
                        choices=[
                            ("real_estate_training", "Real Estate Training"),
                            ("entrepreneurship", "Entrepreneurship Development"),
                            ("business_mentorship", "Business Mentorship Program"),
                            ("industry_networking", "Industry Networking"),
                            ("career_empowerment", "Career Empowerment"),
                            ("youth_development", "Youth Development Initiative"),
                            ("investment_masterclass", "Investment Masterclass"),
                            ("hospitality_training", "Hospitality & Tourism Training"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "experience_level",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner — No Prior Experience"),
                            ("intermediate", "Intermediate — Some Experience"),
                            ("advanced", "Advanced — Experienced Professional"),
                            ("entrepreneur", "Business Owner / Entrepreneur"),
                        ],
                        default="beginner",
                        max_length=20,
                    ),
                ),
                (
                    "preferred_format",
                    models.CharField(
                        choices=[
                            ("online", "Online / Virtual"),
                            ("in_person", "In-Person (Lagos)"),
                            ("hybrid", "Hybrid"),
                            ("self_paced", "Self-Paced / Recorded"),
                        ],
                        default="online",
                        max_length=20,
                    ),
                ),
                (
                    "goals",
                    models.TextField(
                        help_text="What do you hope to achieve from this program?"
                    ),
                ),
                (
                    "how_heard",
                    models.CharField(
                        blank=True,
                        help_text="How did you hear about Nestova Academy?",
                        max_length=200,
                    ),
                ),
                (
                    "referral_name",
                    models.CharField(
                        blank=True,
                        help_text="Name of person who referred you (if any)",
                        max_length=200,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Application Pending"),
                            ("reviewed", "Application Reviewed"),
                            ("accepted", "Accepted"),
                            ("enrolled", "Enrolled / Active"),
                            ("completed", "Program Completed"),
                            ("deferred", "Deferred"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("admin_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="academy_enrollments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Academy Enrollment",
                "verbose_name_plural": "Academy Enrollments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BrokerageInquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None
                    ),
                ),
                (
                    "service_requested",
                    models.CharField(
                        choices=[
                            ("buy_property", "Buy a Property"),
                            ("sell_property", "Sell My Property"),
                            ("shortlet_booking", "Book a Shortlet Apartment"),
                            ("shortlet_listing", "List My Shortlet"),
                            ("interior_design", "Interior Design"),
                            ("smart_security", "SmartShield Security Installation"),
                            ("industrial_cleaning", "Industrial Cleaning Service"),
                            ("realtor_hub", "Realtor / Developer Hub — List Property"),
                            ("property_inspection", "Book a Property Inspection"),
                            ("investment_consulting", "Investment Consulting"),
                            ("property_management", "Property Management"),
                            ("documentation", "Property Documentation Support"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("lagos", "Lagos"),
                            ("abuja", "Abuja"),
                            ("port_harcourt", "Port Harcourt"),
                            ("enugu", "Enugu"),
                            ("owerri", "Owerri"),
                            ("other", "Other Location"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "timeline",
                    models.CharField(
                        choices=[
                            ("urgent", "Urgent — As Soon As Possible"),
                            ("within_month", "Within 1 Month"),
                            ("1_3_months", "1–3 Months"),
                            ("3_6_months", "3–6 Months"),
                            ("flexible", "Flexible / Just Exploring"),
                        ],
                        default="flexible",
                        max_length=20,
                    ),
                ),
                (
                    "budget",
                    models.CharField(
                        blank=True,
                        help_text="Your budget range for this service",
                        max_length=200,
                    ),
                ),
                (
                    "message",
                    models.TextField(help_text="Provide details about what you need"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("contacted", "Client Contacted"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("admin_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("contacted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="brokerage_inquiries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Brokerage Inquiry",
                "verbose_name_plural": "Brokerage Inquiries",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TourismInquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None
                    ),
                ),
                (
                    "inquiry_type",
                    models.CharField(
                        choices=[
                            ("travel_package", "Travel Package / Tour"),
                            ("group_tour", "Group Tour"),
                            ("cultural_tour", "Cultural Heritage Tour"),
                            ("business_tourism", "Business Tourism"),
                            ("educational_tourism", "Educational Tourism"),
                            ("luxury_experience", "Luxury / Lifestyle Experience"),
                            ("hospitality_partnership", "Hospitality Partnership"),
                            (
                                "investment_opportunity",
                                "Tourism Investment Opportunity",
                            ),
                            ("youth_fellowship", "Youth Tourism Fellowship"),
                            ("general", "General Inquiry"),
                        ],
                        default="general",
                        max_length=30,
                    ),
                ),
                (
                    "destination_preference",
                    models.CharField(
                        choices=[
                            ("within_nigeria", "Within Nigeria"),
                            ("west_africa", "West Africa"),
                            ("rest_of_africa", "Rest of Africa"),
                            ("international", "International"),
                            ("not_sure", "Not Sure Yet"),
                        ],
                        default="within_nigeria",
                        max_length=30,
                    ),
                ),
                (
                    "group_size",
                    models.CharField(
                        choices=[
                            ("solo", "Solo (1 Person)"),
                            ("couple", "Couple (2 People)"),
                            ("small", "Small Group (3–10 People)"),
                            ("medium", "Medium Group (11–30 People)"),
                            ("large", "Large Group (30+ People)"),
                        ],
                        default="solo",
                        max_length=20,
                    ),
                ),
                (
                    "budget_range",
                    models.CharField(
                        choices=[
                            ("under_100k", "Under ₦100,000"),
                            ("100k_500k", "₦100,000 – ₦500,000"),
                            ("500k_1m", "₦500,000 – ₦1,000,000"),
                            ("1m_5m", "₦1,000,000 – ₦5,000,000"),
                            ("above_5m", "Above ₦5,000,000"),
                            ("open", "Open / Flexible"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                (
                    "preferred_travel_date",
                    models.DateField(
                        blank=True, help_text="Preferred departure date", null=True
                    ),
                ),
                (
                    "trip_duration",
                    models.CharField(
                        blank=True,
                        help_text="e.g., 3 days, 1 week, 2 weeks",
                        max_length=100,
                    ),
                ),
                (
                    "special_interests",
                    models.CharField(
                        blank=True,
                        help_text="e.g., history, food, adventure, beaches, culture",
                        max_length=300,
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        help_text="Tell us about your dream experience or what you're looking for"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("contacted", "Client Contacted"),
                            ("package_sent", "Package Sent"),
                            ("booked", "Booked / Confirmed"),
                            ("completed", "Trip Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("admin_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("contacted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tourism_inquiries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Tourism Inquiry",
                "verbose_name_plural": "Tourism Inquiries",
                "ordering": ["-created_at"],
            },
        ),
    ]
