# Generated by Django 5.0.4 on 2026-04-21 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0005_alter_apartment_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScrapedListing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("price", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=300)),
                ("url", models.URLField(unique=True)),
                ("image_url", models.URLField(blank=True)),
                ("source", models.CharField(default="propertypro.ng", max_length=100)),
                ("city", models.CharField(default="lagos", max_length=100)),
                ("synced_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-synced_at"],
            },
        ),
    ]
