# Generated by Django 5.0.4 on 2026-04-21 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0006_scrapedlisting"),
    ]

    operations = [
        migrations.AddField(
            model_name="scrapedlisting",
            name="image_file",
            field=models.ImageField(blank=True, upload_to="scraped/"),
        ),
    ]
