# Generated by Django 5.0.4 on 2026-04-21 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0007_scrapedlisting_image_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scrapedlisting",
            name="image_file",
            field=models.ImageField(blank=True, null=True, upload_to="scraped/"),
        ),
    ]
