# Generated by Django 5.0.4 on 2026-07-30 04:38

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0010_alter_propertyapplication_floor_choice_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Developer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=300, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=320, unique=True)),
                (
                    "tagline",
                    models.CharField(
                        blank=True,
                        help_text="Short slogan shown on cards",
                        max_length=300,
                    ),
                ),
                (
                    "description",
                    ckeditor.fields.RichTextField(
                        blank=True, help_text="Full developer profile / about"
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="developers/logos/"
                    ),
                ),
                (
                    "banner_image",
                    models.ImageField(
                        blank=True,
                        help_text="Hero banner shown on the developer detail page",
                        null=True,
                        upload_to="developers/banners/",
                    ),
                ),
                (
                    "headquarters",
                    models.CharField(
                        blank=True, help_text="e.g. Lekki, Lagos", max_length=200
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("phone", models.CharField(blank=True, max_length=30)),
                ("website", models.URLField(blank=True, null=True)),
                ("facebook_page", models.URLField(blank=True, null=True)),
                ("instagram_page", models.URLField(blank=True, null=True)),
                ("linkedin_page", models.URLField(blank=True, null=True)),
                ("x_page", models.URLField(blank=True, null=True)),
                (
                    "founded_year",
                    models.PositiveIntegerField(
                        blank=True, help_text="Year founded", null=True
                    ),
                ),
                (
                    "total_units_delivered",
                    models.PositiveIntegerField(
                        default=0, help_text="Total housing units delivered"
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False,
                        help_text="Show on the homepage developers section",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Developer",
                "verbose_name_plural": "Developers",
                "ordering": ["-is_featured", "name"],
            },
        ),
        migrations.AddField(
            model_name="property",
            name="developer",
            field=models.ForeignKey(
                blank=True,
                help_text="Real estate developer/brand that built or owns this property",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="properties",
                to="property.developer",
            ),
        ),
    ]
