# Generated by Django 5.0.4 on 2026-07-30 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0011_developer_property_developer"),
    ]

    operations = [
        migrations.AddField(
            model_name="developer",
            name="founder_image",
            field=models.ImageField(
                blank=True,
                help_text="Picture of the founder, CEO, or key representative",
                null=True,
                upload_to="developers/founders/",
            ),
        ),
    ]
