# Generated by Django 5.0.4 on 2026-08-08 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0012_developer_founder_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=15, null=True
            ),
        ),
    ]
