# Generated by Django 5.0.4 on 2026-08-11 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0013_alter_property_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("account_name", models.CharField(max_length=300)),
                ("bank_name", models.CharField(max_length=200)),
                ("account_number", models.CharField(max_length=20)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Display order (lower = first)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Payment Account",
                "verbose_name_plural": "Payment Accounts",
                "ordering": ["order", "bank_name"],
            },
        ),
    ]
