# Generated by Django 5.0.4 on 2026-08-15 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0014_paymentaccount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="square_feet",
            field=models.PositiveIntegerField(
                blank=True, help_text="Property size in square feet", null=True
            ),
        ),
    ]
