# Generated by Django 5.0.4 on 2026-08-15 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0015_alter_property_square_feet"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="is_call_for_price",
            field=models.BooleanField(default=False),
        ),
    ]
