# Generated by Django 5.0.4 on 2026-08-25 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0016_property_is_call_for_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='boost_tier',
            field=models.CharField(choices=[('standard', 'Standard'), ('premium', 'Premium (5× exposure)'), ('premium_gold', 'Premium Gold (10× exposure)'), ('sponsored', 'Sponsored (20× exposure)')], db_index=True, default='standard', help_text='Visibility rank: standard, premium, premium_gold, sponsored', max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='boosted_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Timestamp of last push-up / boost', null=True),
        ),
    ]
